package com.shq.oper.model.domain.mongo;

import java.io.Serializable;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Document(collection = "shipping_address")
public class ShippingAddress implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7955881258704626759L;

	/**
	 * 收货地址编号 This field was generated by MyBatis Generator. This field
	 * corresponds to the database column shipping_address.shipping_address_id
	 *
	 * @mbggenerated
	 */
	@Id
	private String shippingAddressId;

	public String getShippingAddressId() {
		return shippingAddressId;
	}

	public void setShippingAddressId(String shippingAddressId) {
		this.shippingAddressId = shippingAddressId;
	}

	/**
	 * 省份 This field was generated by MyBatis Generator. This field corresponds
	 * to the database column shipping_address.province
	 *
	 * @mbggenerated
	 */

	/**
	 * 城市 This field was generated by MyBatis Generator. This field corresponds
	 * to the database column shipping_address.city
	 *
	 * @mbggenerated
	 */

	/**
	 * 详细地址 This field was generated by MyBatis Generator. This field
	 * corresponds to the database column shipping_address.address
	 *
	 * @mbggenerated
	 */
	private String address; //手填地址

	/**
	 * 用户编号 This field was generated by MyBatis Generator. This field
	 * corresponds to the database column shipping_address.user_id
	 *
	 * @mbggenerated
	 */

	/**
	 * 用户名
	 */
	private String userName;
	/**
	 * 邮政编号 This field was generated by MyBatis Generator. This field
	 * corresponds to the database column shipping_address.zip
	 *
	 * @mbggenerated
	 */

	/**
	 * 收件人姓名 This field was generated by MyBatis Generator. This field
	 * corresponds to the database column shipping_address.shipping_name
	 *
	 * @mbggenerated
	 */
	private String shippingName;

	/**
	 * 收件人性别 This field was generated by MyBatis Generator. This field
	 * corresponds to the database column shipping_address.shipping_sex
	 *
	 * @mbggenerated
	 */
	private String shippingSex;
	/**
	 * 收件人电话 This field was generated by MyBatis Generator. This field
	 * corresponds to the database column shipping_address.shipping_telephone
	 *
	 * @mbggenerated
	 */
	private String shippingTelephone;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column shipping_address.shipping_address_id
	 *
	 * @return the value of shipping_address.shipping_address_id
	 *
	 * @mbggenerated
	 */


	private Boolean bDefault; // 是否默认地址

	private String tipDistrict; // 区县
	
	private String tipCity;
	
	private String tipProvince; //省
	
	private String tipId;
	
	private String tipName;
	
	private String tipLocation;
	
	private String tipAddress;
	
	/**
	 * 详细地址 (拼接后的地址)
	 */
	private String addRessDetail;

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}


	public String getTipCity() {
		return tipCity;
	}

	public void setTipCity(String tipCity) {
		this.tipCity = tipCity;
	}

	public String getTipDistrict() {
		return tipDistrict;
	}

	public void setTipDistrict(String tipDistrict) {
		this.tipDistrict = tipDistrict;
	}

	public String getTipId() {
		return tipId;
	}

	public void setTipId(String tipId) {
		this.tipId = tipId;
	}

	public String getTipName() {
		return tipName;
	}

	public void setTipName(String tipName) {
		this.tipName = tipName;
	}

	public String getTipLocation() {
		return tipLocation;
	}

	public void setTipLocation(String tipLocation) {
		this.tipLocation = tipLocation;
	}

	public String getTipAddress() {
		return tipAddress;
	}

	public void setTipAddress(String tipAddress) {
		this.tipAddress = tipAddress;
	}

	/**
	

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column shipping_address.address
	 *
	 * @return the value of shipping_address.address
	 *
	 * @mbggenerated
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column shipping_address.address
	 *
	 * @param address
	 *            the value for shipping_address.address
	 *
	 * @mbggenerated
	 */
	public void setAddress(String address) {
		this.address = address == null ? null : address.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column shipping_address.user_id
	 *
	 * @return the value of shipping_address.user_id
	 *
	 * @mbggenerated
	 */

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column shipping_address.zip
	 *
	 * @return the value of shipping_address.zip
	 *
	 * @mbggenerated

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column shipping_address.shipping_name
	 *
	 * @return the value of shipping_address.shipping_name
	 *
	 * @mbggenerated
	 */
	public String getShippingName() {
		return shippingName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column shipping_address.shipping_name
	 *
	 * @param shippingName
	 *            the value for shipping_address.shipping_name
	 *
	 * @mbggenerated
	 */
	public void setShippingName(String shippingName) {
		this.shippingName = shippingName == null ? null : shippingName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column shipping_address.shipping_telephone
	 *
	 * @return the value of shipping_address.shipping_telephone
	 *
	 * @mbggenerated
	 */
	public String getShippingTelephone() {
		return shippingTelephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column shipping_address.shipping_telephone
	 *
	 * @param shippingTelephone
	 *            the value for shipping_address.shipping_telephone
	 *
	 * @mbggenerated
	 */
	public void setShippingTelephone(String shippingTelephone) {
		this.shippingTelephone = shippingTelephone == null ? null : shippingTelephone.trim();
	}


	public String getTipProvince() {
		return tipProvince;
	}

	public void setTipProvince(String tipProvince) {
		this.tipProvince = tipProvince;
	}

	public String getShippingSex() {
		return shippingSex;
	}

	public void setShippingSex(String shippingSex) {
		this.shippingSex = shippingSex;
	}

	public Boolean getbDefault() {
		return bDefault;
	}

	public void setbDefault(Boolean bDefault) {
		this.bDefault = bDefault;
	}

	public String getAddRessDetail() {
		return addRessDetail;
	}

	public void setAddRessDetail(String addRessDetail) {
		this.addRessDetail = addRessDetail;
	}

}